create table Book(
    id int generated by default as identity primary key,
    title varchar(70) not null,
    year int check (year > 1900) not null,
    format varchar(4) not null,
    alt_cover boolean,
    autograph boolean,
    signature varchar(30)
);
create table Comic(
    id int generated by default as identity primary key,
    book_id int references Book(id) on delete cascade,
    title varchar(70) not null,
    year int check (year > 1900) not null,
    writer varchar(100) not null,
    artist varchar(100) not null
);